version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
    
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
      
  rabbitmq:
    image: rabbitmq:3.6.14
    ports:
      - 5672:5672
      
  elasticsearch:
    image: elasticsearch:5.5.2
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:5.5.2
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch

  logstash:
    image: logstash:5.5.2
    ports:
      - 4560:4560
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on: 
      - elasticsearch
    command: /docker-entrypoint.sh -f /usr/share/logstash/pipeline/logstash.conf
      
 

    