version: '2'
services:
 zabbix-server:
  image: zabbix/zabbix-appliance:alpine-4.0.3
  ports:
   - "10051:10051"
   - "80:80"

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-4.0.3
  ports:
   - "10050:10050"
  links:
   - zabbix-server:zabbix-server
