version: '3'

services:

  influxdb:
    image: influxdb:1.8
    container_name: tick_influxdb
    restart: always
    networks: 
      - tick
    volumes:
      - ./influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
  
  telegraf:
    image: telegraf:1.17
    container_name: tick_telegraf
    restart: always
    depends_on:
      - influxdb
    networks:
      - tick
    links:
      - influxdb
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  
  kapacitor:
    image: kapacitor:1.5
    container_name: tick_kapacitor
    restart: always
    depends_on:
      - influxdb
      - telegraf
    networks:
      - tick
    links:
      - influxdb
      - telegraf
    volumes:
      - ./kapacitor/conf/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro

  chronograf:
    image: chronograf:1.8
    container_name: tick_chronograf
    restart: always
    depends_on:
      - influxdb
      - telegraf
      - kapacitor
    networks: 
      - tick
    links:
      - influxdb
      - telegraf
      - kapacitor
    ports:
      - 8888:8888

  grafana:
    image: grafana/grafana
    container_name: tick_grafana
    restart: always
    depends_on:
      - influxdb
      - telegraf
      - kapacitor
    networks: 
      - tick
    links:
      - influxdb
      - telegraf
      - kapacitor
    ports:
      - 3000:3000
  
  nginx:
    image: nginx:1.19
    container_name: tick_nginx
    restart: always
    depends_on:
      - influxdb
      - telegraf
      - chronograf
      - kapacitor
      - grafana
    networks:
      - tick
    links:
      - influxdb
      - telegraf
      - chronograf
      - kapacitor
      - grafana
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443

networks: 
  tick:
    external: false
    